# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff's GitHub Pages site
email: jjj@stowers.org
description: > # this means to ignore newlines until "baseurl:"
  This is my GitHub Pages site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeffjjohnston.github.io" # the base hostname & protocol for your site
twitter_username: jeffj312
github_username:  jeffjjohnston
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: ""
